version = 1

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "docker"